schemaVersion: '2.0.0'
commandTests:
  - name: "python installation"
    command: "which"
    args: ["python"]
    expectedOutput: ["/usr/local/bin/python\n"]

  - name: "python version"
    command: "python"
    args: ["--version"]
    expectedOutput: ["Python 3.*\n"]

  - name: "Pillow installation"
    command: "pip"
    args: ["show", "Pillow"]
    expectedOutput: [
        "Pillow\n",
        "Version: 6.*\n",
        ]

  - name: "argon2-cffi installation"
    command: "pip"
    args: ["show", "argon2-cffi"]
    expectedOutput: [
        "argon2-cffi\n",
        "Version: 19.*\n",
        ]

  - name: "psycopg2 installation"
    command: "pip"
    args: ["show", "psycopg2"]
    expectedOutput: [
        "psycopg2\n",
        "Version: 2.8.*\n",
        ]
