schemaVersion: '2.0.0'
commandTests:
  - name: "python version"
    command: "python"
    args: ["--version"]
    expectedError: ["Python 2.7.*\n"]

  - name: "flake8 installation"
    command: "pip"
    args: ["show", "flake8"]
    expectedOutput: [
        "flake8\n",
]
